"""
doc_generator.py
================
Generates a Word (.docx) PSO Action Plan from a scored show and LLM outputs.

Sections:
  1. Scope Statement
  2. Show-Level P0 Fixes
  3. Keyword Intelligence Table
  4. Episode Action Plans (P1 full detail, P2 detail, P3 summary table)
  5. 30/60/90-Day Execution Plan
  6. Buzzsprout How-To Guide
"""

import os
from datetime import datetime
from typing import Dict, List, Optional

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from .feed_parser import Episode, Show


# ── Color palette ────────────────────────────────────────────────────────────
CUE_TEAL = RGBColor(0x1A, 0x9E, 0x8F)
CUE_DARK = RGBColor(0x0D, 0x11, 0x17)
RED = RGBColor(0xC0, 0x39, 0x2B)
ORANGE = RGBColor(0xE6, 0x7E, 0x22)
GREEN = RGBColor(0x27, 0xAE, 0x60)
GRAY = RGBColor(0x7F, 0x8C, 0x8D)


def _set_cell_bg(cell, hex_color: str):
    """Set table cell background color."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def _heading(doc: Document, text: str, level: int = 1):
    p = doc.add_heading(text, level=level)
    run = p.runs[0] if p.runs else p.add_run(text)
    run.font.color.rgb = CUE_TEAL
    return p


def _priority_color(priority: str) -> RGBColor:
    return {
        "P0": RED,
        "P1": RED,
        "P2": ORANGE,
        "P3": GREEN,
    }.get(priority, GRAY)


class DocGenerator:
    """
    Generates a Word document PSO Action Plan.

    Usage:
        gen = DocGenerator()
        gen.generate(show, keyword_intelligence, llm_outputs, "output/MGM_PSO.docx")
    """

    def __init__(self):
        pass

    def generate(
        self,
        show: Show,
        keyword_intelligence: Dict,
        llm_outputs: Dict[str, Optional[Dict]],
        output_path: str,
    ):
        """
        Generate the full Word document.

        show: parsed and scored Show object
        keyword_intelligence: {keyword: {apple_rank, spotify_rank, demand, difficulty, competitors}}
        llm_outputs: {episode_guid: llm_metadata_dict_or_None}
        output_path: where to save the .docx
        """
        doc = Document()
        self._set_styles(doc)

        # Cover
        self._add_cover(doc, show)

        # Section 1: Scope
        self._add_scope(doc)

        # Section 2: Show-Level P0
        self._add_show_p0(doc, show)

        # Section 3: Keyword Intelligence
        self._add_keyword_intelligence(doc, keyword_intelligence)

        # Section 4: Episode Action Plans
        p1 = [e for e in show.episodes if e.priority == "P1"][:20]
        p2 = [e for e in show.episodes if e.priority == "P2"][:50]
        p3 = [e for e in show.episodes if e.priority == "P3"]

        self._add_episode_section(doc, p1, llm_outputs, "P1 — Fix Immediately (Top 20)", RED)
        self._add_episode_section(doc, p2, llm_outputs, "P2 — Fix This Week (Next 50)", ORANGE)
        self._add_p3_table(doc, p3)

        # Section 5: 30/60/90 Plan
        self._add_execution_plan(doc, show)

        # Section 6: Buzzsprout How-To
        self._add_howto(doc)

        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        doc.save(output_path)
        print(f"[DocGenerator] Saved: {output_path}")

    # ── Private helpers ──────────────────────────────────────────────────────

    def _set_styles(self, doc: Document):
        style = doc.styles["Normal"]
        style.font.name = "Calibri"
        style.font.size = Pt(11)

    def _add_cover(self, doc: Document, show: Show):
        doc.add_paragraph()
        title = doc.add_paragraph()
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title.add_run("CUE PSO ACTION PLAN")
        run.font.size = Pt(28)
        run.font.bold = True
        run.font.color.rgb = CUE_TEAL

        sub = doc.add_paragraph()
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub.add_run(show.title).font.size = Pt(18)

        meta = doc.add_paragraph()
        meta.alignment = WD_ALIGN_PARAGRAPH.CENTER
        meta.add_run(
            f"Generated by Cue PSO Plugin  ·  {datetime.now().strftime('%B %d, %Y')}"
        ).font.color.rgb = GRAY

        p1_count = sum(1 for e in show.episodes if e.priority == "P1")
        p2_count = sum(1 for e in show.episodes if e.priority == "P2")
        p3_count = sum(1 for e in show.episodes if e.priority == "P3")

        stats = doc.add_paragraph()
        stats.alignment = WD_ALIGN_PARAGRAPH.CENTER
        stats.add_run(
            f"Total Episodes: {len(show.episodes)}  ·  "
            f"P1: {p1_count}  ·  P2: {p2_count}  ·  P3: {p3_count}"
        )
        doc.add_page_break()

    def _add_scope(self, doc: Document):
        _heading(doc, "1 — What This Document Is", 1)
        doc.add_paragraph(
            "This is a Podcast Search Optimization (PSO) Action Plan generated by the Cue PSO Plugin. "
            "It uses live data from the Apple iTunes Search API, Spotify Web API, and Google Trends — "
            "the same underlying data sources used by Ausha's $50/month PSO Control Panel — "
            "combined with Cue's built-in AI to write replacement metadata for you."
        )
        doc.add_paragraph(
            "Every keyword recommendation in this document is sourced from live Apple Podcasts "
            "search rank data (rank order = what listeners see first), competitor RSS metadata, "
            "and Google Trends demand signals. No keywords are guessed or fabricated."
        )
        doc.add_paragraph(
            "The AI-generated metadata (titles, descriptions, tags, chapters) is produced by "
            "Cue's own built-in language model. No third-party AI service (OpenAI, Anthropic, etc.) "
            "is used. All data remains within the Cue platform."
        )

    def _add_show_p0(self, doc: Document, show: Show):
        _heading(doc, "2 — P0: Show-Level Global Fixes", 1)
        doc.add_paragraph(
            "These fixes apply to the show as a whole and affect every episode's discoverability. "
            "Fix these before touching individual episodes."
        )
        items = [
            ("Show Description", "The show description is the first thing Apple Podcasts indexes. "
             "It must open with your primary keyword (e.g., 'michigan politics') in the first sentence. "
             "Remove all boilerplate from the top. Current description should be audited in Buzzsprout → Show → Edit."),
            ("Author Tag", "The iTunes Author field should match your show's primary keyword cluster, "
             "not just your name. Example: 'Michigan Politics Podcast by [Your Name]'."),
            ("Show Category", "Verify your primary category is 'News > Politics' and secondary is "
             "'Society & Culture > Commentary'. Wrong categories suppress discovery."),
            ("Artwork Alt Text", "Buzzsprout does not expose alt text, but your artwork filename "
             "should include your primary keyword when uploaded."),
        ]
        for field_name, guidance in items:
            p = doc.add_paragraph(style="List Bullet")
            run = p.add_run(f"{field_name}: ")
            run.bold = True
            run.font.color.rgb = RED
            p.add_run(guidance)

    def _add_keyword_intelligence(self, doc: Document, keyword_intelligence: Dict):
        _heading(doc, "3 — Keyword Intelligence", 1)
        doc.add_paragraph(
            "Keywords are ranked by opportunity: high demand + low difficulty = highest priority. "
            "Apple Rank and Spotify Rank are live positions from the respective search APIs. "
            "Demand is a 0–100 Google Trends interest score. Difficulty is calculated from "
            "competitor count, episode depth, and recency."
        )

        if not keyword_intelligence:
            doc.add_paragraph("No keyword intelligence data available for this run.")
            return

        table = doc.add_table(rows=1, cols=6)
        table.style = "Table Grid"
        headers = ["Keyword", "Apple Rank", "Spotify Rank", "Demand", "Difficulty", "Status"]
        for i, h in enumerate(headers):
            cell = table.rows[0].cells[i]
            cell.text = h
            cell.paragraphs[0].runs[0].bold = True
            _set_cell_bg(cell, "1A9E8F")
            cell.paragraphs[0].runs[0].font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

        for kw, data in keyword_intelligence.items():
            row = table.add_row().cells
            row[0].text = kw
            row[1].text = f"#{data.get('apple_rank', 'N/A')}" if data.get('apple_rank') else "Not ranked"
            row[2].text = f"#{data.get('spotify_rank', 'N/A')}" if data.get('spotify_rank') else "Not ranked"
            row[3].text = str(data.get("demand", "—"))
            diff = data.get("difficulty", {})
            row[4].text = f"{diff.get('label', '—')} ({diff.get('score', '—')})"
            status = "Ranking" if data.get("apple_rank") else "Opportunity"
            row[5].text = status

        doc.add_paragraph()

    def _add_episode_section(
        self, doc: Document, episodes: List[Episode],
        llm_outputs: Dict, section_title: str, color: RGBColor
    ):
        _heading(doc, f"4 — {section_title}", 1)

        for ep in episodes:
            _heading(doc, ep.title[:80], 2)
            llm = llm_outputs.get(ep.guid)

            # Metadata row
            table = doc.add_table(rows=1, cols=4)
            table.style = "Table Grid"
            cells = table.rows[0].cells
            cells[0].text = f"PSO Score: {ep.pso_score}/100"
            cells[1].text = f"Priority: {ep.priority}"
            cells[2].text = f"Apple Rank: {ep.apple_rank or 'N/A'}"
            cells[3].text = f"Spotify Rank: {ep.spotify_rank or 'N/A'}"
            for cell in cells:
                cell.paragraphs[0].runs[0].bold = True

            doc.add_paragraph()

            # Safety flags
            if ep.safety_flags:
                p = doc.add_paragraph()
                r = p.add_run(f"⚠ SAFETY FLAGS: {', '.join(ep.safety_flags)}")
                r.font.color.rgb = RED
                r.bold = True

            # Current vs AI-generated
            if llm:
                # Title
                p = doc.add_paragraph()
                p.add_run("Current Title: ").bold = True
                p.add_run(ep.title)

                p = doc.add_paragraph()
                r = p.add_run("AI-Generated Title: ")
                r.bold = True
                r.font.color.rgb = GREEN
                p.add_run(llm.get("title", ""))

                # Description
                p = doc.add_paragraph()
                p.add_run("AI-Generated Opening (first 150 words): ").bold = True

                desc_p = doc.add_paragraph(llm.get("description_opening", ""))
                desc_p.paragraph_format.left_indent = Inches(0.3)

                # Tags
                p = doc.add_paragraph()
                p.add_run("Replacement Tags (PSO-ordered): ").bold = True
                tags = llm.get("tags", [])
                p.add_run(" | ".join(tags))

                # Chapters
                chapters = llm.get("chapters", [])
                if chapters:
                    p = doc.add_paragraph()
                    p.add_run("Chapter Names: ").bold = True
                    for ch in chapters:
                        doc.add_paragraph(
                            f"({ch.get('time', '00:00')}) {ch.get('name', '')}",
                            style="List Bullet"
                        )

                # Safety rewrites
                safety_rw = llm.get("safety_rewrites", {})
                if safety_rw:
                    p = doc.add_paragraph()
                    r = p.add_run("Safety Rewrites: ")
                    r.bold = True
                    r.font.color.rgb = RED
                    for orig, safe in safety_rw.items():
                        doc.add_paragraph(
                            f'"{orig}" → "{safe}"',
                            style="List Bullet"
                        )
            else:
                # No LLM output — show manual fix guidance
                p = doc.add_paragraph()
                p.add_run("Manual Fix Required: ").bold = True
                p.add_run(
                    "Move boilerplate to bottom of description. "
                    "Rewrite title to lead with primary topic keyword. "
                    "Replace dead tags with specific niche terms."
                )

            doc.add_paragraph()

    def _add_p3_table(self, doc: Document, episodes: List[Episode]):
        _heading(doc, "4 — P3: Archive Backfill (Summary Table)", 1)
        doc.add_paragraph(
            f"These {len(episodes)} episodes are lower priority. "
            "Apply the same boilerplate-removal and tag-replacement process "
            "after completing all P1 and P2 episodes."
        )

        if not episodes:
            return

        table = doc.add_table(rows=1, cols=4)
        table.style = "Table Grid"
        for i, h in enumerate(["Episode Title", "PSO Score", "Primary Issue", "Est. Fix Time"]):
            cell = table.rows[0].cells[i]
            cell.text = h
            cell.paragraphs[0].runs[0].bold = True

        for ep in episodes:
            row = table.add_row().cells
            row[0].text = ep.title[:60]
            row[1].text = str(ep.pso_score)
            issue = "Boilerplate" if ep.pso_score < 60 else "Dead tags" if ep.tags else "Tags missing"
            row[2].text = issue
            row[3].text = "5–8 min"

    def _add_execution_plan(self, doc: Document, show: Show):
        _heading(doc, "5 — 30/60/90-Day Execution Plan", 1)
        p1_count = sum(1 for e in show.episodes if e.priority == "P1")
        p2_count = sum(1 for e in show.episodes if e.priority == "P2")

        plan = [
            ("Week 1–2 (Days 1–14)", "P0 show-level fixes",
             "Fix show description, author tag, and category in Buzzsprout. "
             "These propagate to all platforms within 48 hours."),
            ("Week 3–4 (Days 15–30)", f"P1 top 20 episodes ({p1_count} total)",
             "Use the AI-generated metadata in Section 4. Copy title, description opening, "
             "and tags directly into Buzzsprout. Add chapters. "
             f"Target: 10–15 min per episode × 20 episodes = ~4–5 hours total."),
            ("Week 5–8 (Days 31–60)", f"P2 next 50 episodes ({p2_count} total)",
             "Same workflow as P1. Focus on boilerplate removal and tag replacement. "
             "Run a new PSO audit at Day 45 to check rank movement."),
            ("Week 9–12 (Days 61–90)", "P3 archive + new episode workflow",
             "Backfill P3 episodes. Establish a new episode PSO checklist: "
             "every new episode gets keyword research before publishing. "
             "Set up weekly rank tracking in Cue to monitor Apple + Spotify positions."),
        ]

        for period, focus, detail in plan:
            p = doc.add_paragraph()
            r = p.add_run(f"{period} — {focus}")
            r.bold = True
            r.font.color.rgb = CUE_TEAL
            doc.add_paragraph(detail)

    def _add_howto(self, doc: Document):
        _heading(doc, "6 — Buzzsprout Step-by-Step", 1)
        steps = [
            "Log in to Buzzsprout → click Episodes in the left sidebar.",
            "Click the episode title → click Edit Episode.",
            "DESCRIPTION: Scroll to the description field. Cut the fan mail / BuyMeACoffee / sponsor block from the top. Paste it after the last paragraph of episode content. Paste the AI-Generated Opening from Section 4 at the very top.",
            "TITLE: Replace with the AI-Generated Title from Section 4. Verify it is under 80 characters.",
            "TAGS: Delete all existing tags. Paste the Replacement Tags from Section 4, one per field.",
            "CHAPTERS: In the description body, add chapter timestamps using the format: (00:00) Chapter Name — one per line.",
            "Click Save. Changes propagate to Apple Podcasts, Spotify, and all directories within 24–48 hours.",
            "Estimated time per episode: 10–20 minutes for P1 episodes with AI-generated metadata ready.",
        ]
        for i, step in enumerate(steps, 1):
            p = doc.add_paragraph(style="List Number")
            p.add_run(step)
