"""
core/doc_generator.py
=====================
Word document output for the YouTube PSO plugin.
Generates a structured .docx action plan with:
  - Keyword intelligence table
  - Difficulty and PSO score per keyword
  - Competitor channel profiles
  - Per-video replacement metadata (title, description, hook, chapters, tags)
  - 30/60/90-day tracking plan
  - YouTube upload checklist
"""

import os
import logging
from typing import List, Optional, Dict, Any
from datetime import datetime

from docx import Document
from docx.shared import Pt, RGBColor, Inches
from docx.enum.text import WD_ALIGN_PARAGRAPH
from docx.oxml.ns import qn
from docx.oxml import OxmlElement

from .search_rank import KeywordRankResult
from .difficulty_scorer import DifficultyResult
from .competitor_scraper import CompetitorProfile
from .keyword_classifier import ClassifiedKeyword

logger = logging.getLogger(__name__)


def _set_cell_bg(cell, hex_color: str):
    """Set background color of a table cell."""
    tc = cell._tc
    tcPr = tc.get_or_add_tcPr()
    shd = OxmlElement("w:shd")
    shd.set(qn("w:val"), "clear")
    shd.set(qn("w:color"), "auto")
    shd.set(qn("w:fill"), hex_color)
    tcPr.append(shd)


def _add_heading(doc: Document, text: str, level: int = 1, color: str = "1A1A2E"):
    para = doc.add_heading(text, level=level)
    for run in para.runs:
        run.font.color.rgb = RGBColor.from_string(color)
    return para


def _add_table_row(table, cells: List[str], bold: bool = False, bg: Optional[str] = None):
    row = table.add_row()
    for i, text in enumerate(cells):
        cell = row.cells[i]
        cell.text = text
        if bold:
            for para in cell.paragraphs:
                for run in para.runs:
                    run.bold = True
        if bg:
            _set_cell_bg(cell, bg)
    return row


class YouTubePSODocGenerator:
    """
    Generates a Word document PSO action plan for a YouTube channel.
    """

    BRAND_DARK = "0D1117"
    BRAND_TEAL = "00B4D8"
    BRAND_GOLD = "FFB703"
    BRAND_RED = "C1121F"
    BRAND_GREEN = "2DC653"
    BRAND_GRAY = "6B7280"

    def __init__(self, channel_name: str = "The MiddleGround Mic"):
        self.channel_name = channel_name

    def generate(
        self,
        keyword_results: List[KeywordRankResult],
        difficulty_results: List[DifficultyResult],
        competitor_profiles: List[CompetitorProfile],
        classified_keywords: List[ClassifiedKeyword],
        generated_metadata: List[Dict[str, Any]],
        output_path: str = "output/YouTube_PSO_Action_Plan.docx",
    ) -> str:
        """
        Generate the full YouTube PSO action plan Word document.

        Returns:
            Absolute path to the generated .docx file.
        """
        os.makedirs(os.path.dirname(output_path) or ".", exist_ok=True)
        doc = Document()

        # ── Title page ────────────────────────────────────────────────────────
        title = doc.add_paragraph()
        title.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = title.add_run(f"Cue YouTube PSO Action Plan")
        run.bold = True
        run.font.size = Pt(24)

        sub = doc.add_paragraph()
        sub.alignment = WD_ALIGN_PARAGRAPH.CENTER
        sub.add_run(f"{self.channel_name}  ·  Generated {datetime.now().strftime('%B %d, %Y')}")

        doc.add_paragraph(
            "This document is generated by the Cue Platform Intelligence Plugin using the "
            "YouTube Data API v3 (free, 10,000 units/day), YouTube autocomplete, and "
            "competitor channel metadata. All keyword signals are live-detected — "
            "not estimated from historical data."
        )

        doc.add_page_break()

        # ── Section 1: What This Is ───────────────────────────────────────────
        _add_heading(doc, "Section 1 — What This Document Is", level=1)
        doc.add_paragraph(
            "This is a YouTube Search Optimization (PSO) action plan. It tells you:\n"
            "  • Which keywords your channel currently ranks for on YouTube search\n"
            "  • Which keywords have high demand and low competition (best opportunities)\n"
            "  • What the top-ranking channels in your niche are using in their titles and tags\n"
            "  • Replacement titles, descriptions, hooks, and chapter names for your videos\n\n"
            "What this is NOT: a guarantee of rank improvement. YouTube's algorithm weighs "
            "watch time, click-through rate, and engagement alongside metadata. "
            "Fixing metadata is the first step — not the only step."
        )

        # ── Section 2: Keyword Intelligence ──────────────────────────────────
        doc.add_page_break()
        _add_heading(doc, "Section 2 — Keyword Intelligence", level=1)
        doc.add_paragraph(
            "Keywords are classified by detection source. Priority order:\n"
            "  DETECTED — confirmed in YouTube autocomplete (highest value)\n"
            "  COMPETITOR — extracted from top-ranking video titles and tags\n"
            "  LOCAL — geographic identifiers for your niche\n"
            "  GUEST — named entities (people, organizations)\n"
            "  DEAD — generic terms with no search specificity (remove from tags)"
        )

        if classified_keywords:
            table = doc.add_table(rows=1, cols=4)
            table.style = "Table Grid"
            hdr = table.rows[0].cells
            for i, h in enumerate(["Keyword", "Classification", "Source", "Confidence"]):
                hdr[i].text = h
                for para in hdr[i].paragraphs:
                    for run in para.runs:
                        run.bold = True
                _set_cell_bg(hdr[i], self.BRAND_DARK)
                for para in hdr[i].paragraphs:
                    for run in para.runs:
                        run.font.color.rgb = RGBColor(255, 255, 255)

            for ck in classified_keywords:
                row = table.add_row()
                row.cells[0].text = ck.keyword
                row.cells[1].text = ck.classification
                row.cells[2].text = ck.source[:80]
                row.cells[3].text = ck.confidence
                if ck.classification == "DEAD":
                    _set_cell_bg(row.cells[1], "FFE0E0")
                elif ck.classification == "DETECTED":
                    _set_cell_bg(row.cells[1], "E0FFE8")

        # ── Section 3: PSO Scores ─────────────────────────────────────────────
        doc.add_page_break()
        _add_heading(doc, "Section 3 — PSO Scores and Difficulty", level=1)
        doc.add_paragraph(
            "PSO Score = (Demand × (100 - Difficulty)) / 100\n"
            "Higher PSO Score = better opportunity. Target keywords with PSO Score ≥ 60 first."
        )

        if difficulty_results:
            table = doc.add_table(rows=1, cols=7)
            table.style = "Table Grid"
            headers = ["Keyword", "Your Rank", "PSO Score", "Difficulty", "Demand", "Competitors", "Recommendation"]
            hdr = table.rows[0].cells
            for i, h in enumerate(headers):
                hdr[i].text = h
                for para in hdr[i].paragraphs:
                    for run in para.runs:
                        run.bold = True
                _set_cell_bg(hdr[i], self.BRAND_DARK)
                for para in hdr[i].paragraphs:
                    for run in para.runs:
                        run.font.color.rgb = RGBColor(255, 255, 255)

            for dr in difficulty_results:
                row = table.add_row()
                row.cells[0].text = dr.keyword
                row.cells[1].text = dr.rank_label
                row.cells[2].text = str(dr.pso_score)
                row.cells[3].text = f"{dr.difficulty} ({dr.difficulty_label})"
                row.cells[4].text = str(dr.demand_score)
                row.cells[5].text = str(dr.competitor_count)
                row.cells[6].text = dr.recommendation[:120]
                if dr.pso_score >= 60:
                    _set_cell_bg(row.cells[2], "E0FFE8")
                elif dr.pso_score >= 35:
                    _set_cell_bg(row.cells[2], "FFFDE0")
                else:
                    _set_cell_bg(row.cells[2], "FFE0E0")

        # ── Section 4: Competitor Profiles ────────────────────────────────────
        if competitor_profiles:
            doc.add_page_break()
            _add_heading(doc, "Section 4 — Competitor Channel Profiles", level=1)
            doc.add_paragraph(
                "These channels rank most frequently for your target keywords. "
                "Their title patterns and tag choices are the benchmark for your niche."
            )
            for profile in competitor_profiles[:5]:
                _add_heading(doc, profile.channel_title, level=2)
                doc.add_paragraph(
                    f"Subscribers: {profile.subscriber_count:,}  ·  "
                    f"Videos analyzed: {len(profile.top_videos)}"
                )
                top_terms = list(profile.common_title_terms.items())[:10]
                if top_terms:
                    doc.add_paragraph("Top title terms: " + ", ".join(
                        f"{term} ({count})" for term, count in top_terms
                    ))

        # ── Section 5: Replacement Metadata ──────────────────────────────────
        if generated_metadata:
            doc.add_page_break()
            _add_heading(doc, "Section 5 — Replacement Metadata", level=1)
            doc.add_paragraph(
                "AI-generated replacement titles, descriptions, hooks, and chapters "
                "for your highest-opportunity videos. Generated by Cue's built-in LLM — "
                "no third-party model."
            )
            for i, meta in enumerate(generated_metadata, 1):
                _add_heading(doc, f"Video {i}: {meta.get('original_title', 'Untitled')}", level=2)

                doc.add_paragraph("CURRENT TITLE:").runs[0].bold = True
                doc.add_paragraph(meta.get("original_title", ""))

                doc.add_paragraph("GENERATED TITLE:").runs[0].bold = True
                title_para = doc.add_paragraph(meta.get("title", ""))
                title_para.runs[0].bold = True

                doc.add_paragraph("HOOK (first 30 seconds):").runs[0].bold = True
                doc.add_paragraph(meta.get("hook", ""))

                chapters = meta.get("chapters", [])
                if chapters:
                    doc.add_paragraph("CHAPTERS:").runs[0].bold = True
                    for ch in chapters:
                        doc.add_paragraph(f"  {ch.get('timestamp', '00:00')}  {ch.get('name', '')}")

                doc.add_paragraph("GENERATED DESCRIPTION:").runs[0].bold = True
                doc.add_paragraph(meta.get("description", "")[:800])

                tags = meta.get("tags", [])
                if tags:
                    doc.add_paragraph("TAGS (PSO order):").runs[0].bold = True
                    doc.add_paragraph(", ".join(tags))

                safety = meta.get("safety_notes", [])
                if safety:
                    doc.add_paragraph("POLITICAL SAFETY FIXES:").runs[0].bold = True
                    for note in safety:
                        doc.add_paragraph(f"  • {note}")

                pso_note = meta.get("pso_notes", "")
                if pso_note:
                    doc.add_paragraph(f"PSO NOTE: {pso_note}")

                doc.add_paragraph("")

        # ── Section 6: 30/60/90-Day Plan ─────────────────────────────────────
        doc.add_page_break()
        _add_heading(doc, "Section 6 — 30/60/90-Day Tracking Plan", level=1)

        tracking_rows = [
            ("Days 1–7", "Apply replacement metadata to top 5 PSO Score videos. Note current rank for each keyword."),
            ("Days 8–14", "Check rank for each keyword manually (YouTube search, incognito). Record position."),
            ("Days 15–21", "Apply metadata to next 5 videos. Compare click-through rate in YouTube Studio."),
            ("Days 22–30", "Re-run Cue PSO analysis. Compare new ranks to baseline. Identify movement."),
            ("Days 31–60", "Target MEDIUM difficulty keywords. Apply to 10 more videos. Track watch time."),
            ("Days 61–90", "Evaluate HIGH difficulty keywords. Build content strategy around top 3 opportunities."),
        ]
        table = doc.add_table(rows=1, cols=2)
        table.style = "Table Grid"
        hdr = table.rows[0].cells
        hdr[0].text = "Timeframe"
        hdr[1].text = "Action"
        for cell in hdr:
            for para in cell.paragraphs:
                for run in para.runs:
                    run.bold = True
            _set_cell_bg(cell, self.BRAND_DARK)
            for para in cell.paragraphs:
                for run in para.runs:
                    run.font.color.rgb = RGBColor(255, 255, 255)

        for period, action in tracking_rows:
            row = table.add_row()
            row.cells[0].text = period
            row.cells[1].text = action

        # ── Section 7: YouTube Upload Checklist ──────────────────────────────
        doc.add_page_break()
        _add_heading(doc, "Section 7 — YouTube Upload Checklist", level=1)
        checklist_items = [
            "Title is under 60 characters and leads with topic/entity",
            "Title uses a tension word (fight, exposed, blocked, revealed, ignored, missed)",
            "Title does NOT start with Episode, Ep., Interview, or a number",
            "First 150 characters of description are keyword-rich — no boilerplate, no links",
            "Description has minimum 3 chapters in MM:SS format",
            "First chapter is 00:00",
            "Chapter names are specific — not Introduction, Main Topic, Conclusion",
            "All links, subscribe asks, and social handles are BELOW the chapters",
            "Tags are in PSO order: DETECTED → COMPETITOR → LOCAL → ENTITY → BRAND",
            "No dead tags: video, youtube, channel, subscribe, episode, interview, podcast",
            "Political safety: no unattributed strong claims (rigged, fraud, traitor, scam)",
            "Thumbnail text matches the title argument — no misleading image",
            "Hook (first 30 seconds) opens with tension — not 'Welcome back'",
            "End screen added at final 20 seconds",
            "Captions/subtitles uploaded or auto-generated and reviewed",
        ]
        for item in checklist_items:
            para = doc.add_paragraph(style="List Bullet")
            para.add_run(f"☐  {item}")

        doc.save(output_path)
        logger.info(f"YouTube PSO action plan saved to {output_path}")
        return os.path.abspath(output_path)
